import "./globals.css";
import Navbar from "./navbar";
import Nav from "./nav";
import GlobalCursor from "@/components/GlobalCursor";
import { Geist, Geist_Mono } from "next/font/google";

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <Navbar />
        <main className="relative z-10">{children}</main>
        <GlobalCursor />
      </body>
    </html>
  );
}
